import type { Metadata } from 'next'
import { cn } from "@/lib/utils";
import { Inter } from 'next/font/google'
import './globals.css'
import Nav from '@/components/nav';

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn("min-h-screen bg-background font-sans antialiased", inter.variable)}>
        <Nav />
        <section className=' min-h-screen flex-col p-24 justify-between items-center'>
          {children}
        </section>
      </body>
    </html>
  )
}
